FROM node:16

# https://docs.docker.jp/engine/reference/builder.html#workdir
WORKDIR /biblysm_www

COPY package.json ./
RUN npm install

COPY . .

# Gooogle Cloud Run は 8080 でないといけない
EXPOSE 8080

# ENV PORT を設定すればポートをそれが起動時のポートになるらしい
ENV PORT 8080
ENV HOST 0.0.0.0

#RUN npm run build

CMD [ "npm", "run", "dev" ]
